# Generated by Django 6.0.7 on 2026-07-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jennie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['id'], 'verbose_name': 'цвет', 'verbose_name_plural': 'цвета'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['id'], 'verbose_name': 'материал', 'verbose_name_plural': 'материалы'},
        ),
    ]
